name: task_pp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.18
  sizer: ^2.0.15
  get_it: ^7.2.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
